# Generated by Django 3.0.2 on 2020-01-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dono', '0002_auto_20200113_1503'),
        ('gatinho', '0004_auto_20200110_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatinho',
            name='dono',
            field=models.ManyToManyField(to='dono.Dono'),
        ),
    ]
